// News Card Component
const NewsCard = ({ news, onClick }) => {
  return (
    <div 
      className="bg-white rounded-lg overflow-hidden shadow-md hover:shadow-lg transition-shadow duration-300 cursor-pointer"
      onClick={() => onClick(news.id)}
    >
      <img src={news.image} alt={news.title} className="w-full h-48 object-cover" />
      <div className="p-6">
        <div className="flex justify-between items-center mb-2">
          <p className="text-indigo-700 text-sm font-semibold">{news.date}</p>
          <div className="flex items-center text-gray-500 text-sm">
            <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
            </svg>
            {news.views.toLocaleString()}
          </div>
        </div>
        <h3 className="text-xl font-bold mb-3">{news.title}</h3>
        <p className="text-gray-600 mb-4">{news.excerpt}</p>
        <button className="text-indigo-800 font-semibold hover:underline">Read more →</button>
      </div>
    </div>
  );
};

// Trending News Section Component
const TrendingNewsSection = ({ onNewsSelect }) => {
  return (
    <div>
      <h2 className="text-2xl font-bold mb-6">Trending Book News</h2>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {newsItems.map(news => (
          <NewsCard key={news.id} news={news} onClick={onNewsSelect} />
        ))}
      </div>
    </div>
  );
};