[build]
# Specify the frontend directory and build commands for Vite
app_dir = "frontend"
build_cmd = "npm install && npm run build"  # Install dependencies and build the frontend

[backend]
# Specify the backend directory and build commands for Express
app_dir = "backend"
build_cmd = "npm install && npm run start"  # Install dependencies and start the backend
